version: '3'

services:
  dub:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "localhost:3000"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 1s
    env_file:
      - .env
    volumes:
      - ./data:/app/data