name: lisek!ci

on:
  push:
    branches: ["*"]
  pull_request:
  merge_group:

env:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

jobs:
  docker-build:
    runs-on: ubuntu-latest
    image: docker:cli
    services:
      - docker:dind
    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
    # Default branch is also tagged with `latest`
    script:
      - docker build --pull -t "$DOCKER_IMAGE_NAME" .
      - docker push "$DOCKER_IMAGE_NAME"
      - |
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
          docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
          docker push "$CI_REGISTRY_IMAGE:latest"
        fi
  docker-deploy:
    container: alpine:latest
    stage: deploy
    script:
      - apk update
      - apk add openssh libcrypto3
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - touch ~/.ssh/config
      - touch ~/.ssh/known_hosts
      - chmod -R 400 ~/.ssh
      - ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - ssh $USER@$HOST "cd /root/dub-rs && docker compose pull && docker compose up -d"