name: lisek!ci

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: ${{ secrets.CI_REGISTRY_IMAGE }}:${{ secrets.CI_COMMIT_REF_SLUG }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker BuildX
        uses: docker/setup-buildx-action@v3
      -
        name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{env.REGISTRY}}/osu-lisek/dub-rs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      -
        name: APK installation
        run: |
          apk update
          apk add openssh libcrypto3
      -
        name: SSH configuration
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          touch ~/.ssh/config
          touch ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod -R 400 ~/.ssh
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      -
        name: Docker Compose Update
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USER }}@${{ secrets.HOST }} "docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && cd /root/dub-rs && docker compose pull && docker compose up -d"
