name: lisek!ci

on: [push]

env:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

jobs:
  docker-build:
    runs-on: ubuntu-latest
    image: docker:cli
    services:
      - docker:dind
    steps:
      - run: docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
      - run: docker build --pull -t "$DOCKER_IMAGE_NAME" .
      - run: docker push "$DOCKER_IMAGE_NAME"
      - run: |
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
          docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
          docker push "$CI_REGISTRY_IMAGE:latest"
        fi
  docker-deploy:
    container: alpine:latest
    stage: deploy
    steps:
      - run: apk update
      - run: apk add openssh libcrypto3
      - run: eval $(ssh-agent -s)
      - run: echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/config
      - run: touch ~/.ssh/known_hosts
      - run: chmod -R 400 ~/.ssh
      - run: ssh-keyscan $HOST >> ~/.ssh/known_hosts
      - run: '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - run: ssh $USER@$HOST "cd /root/dub-rs && docker compose pull && docker compose up -d"